[workspace]
resolver = "2"
members = [
    "crates/common",
    "crates/authn",
    "crates/authz-rbac",
    "crates/api-registry",
    "crates/admission",
    "crates/api-types",
    "crates/storage",
    "crates/storage-etcd",
    "crates/controller-runtime",
    "crates/scheduler",
    "crates/node-runtime",
    "crates/api-server",
    "integration-tests",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.91"
license = "Apache-2.0"
repository = "https://github.com/CMAULTOP/kubernetes"

[workspace.dependencies]
async-stream = "=0.3.6"
axum = "=0.7.9"
base64 = "=0.22.1"
etcd-client = "=0.16.0"
futures-util = "=0.3.34"
http = "=1.2.0"
idna_adapter = "=1.1.0"
reqwest = { version = "=0.12.12", default-features = false, features = ["json", "stream"] }
serde = { version = "=1.0.217", features = ["derive"] }
serde_json = "=1.0.134"
subtle = "=2.6.1"
thiserror = "=1.0.69"
time = { version = "=0.3.36", features = ["formatting", "macros", "serde", "parsing"] }
tokio = { version = "=1.42.0", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tower = { version = "=0.5.2", features = ["util"] }
uuid = { version = "=1.11.0", features = ["serde", "v4"] }
