[package]
name = "rusternetes-authn"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
jsonwebtoken.workspace = true
serde.workspace = true
rusternetes-common = { path = "../common" }
subtle.workspace = true

[dev-dependencies]
